### PR TITLE
utilize latest go sdk to ensure createVolume idempotency

### LINKED ISSUE #165: Race condition in CreateVolume
/kind bug

**What happened?**

When the CO calls `CreateVolume` (through the sidecar container), it passes in a volume name. If a second call to create the volume is issued, we return the same volume created in the first request.

Since there's no way to specify the volume name through the EC2 API, we currently set the volume name as a [tag](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/e014aa97b76420bb2d4a92428242a77766095d23/pkg/cloud/cloud.go#L219-L225). However, this workaround has its own problems. 

Imagine this situation:

* `CreateVolume` is called so a volume named `volume1` is created.
* EC2's `CreateVolumeWithContext` is called and it takes about 15 seconds to effectively create the volume.
* `CreateVolume` is called again, but the call above is not done yet.
* The driver will check if a volume with this name already exists, but it won't find any, so it creates the new volume.
* Now we have 2 volumes tagged with the same name.

During attach, for instance, the driver will notice that there's more than one volume with the same name, so it'll return an error. However, this is just a workaround and a proper solution should ideally be implemented on the EC2 side.

This could be achieved by having a `Name` filed in `ec2.CreateVolumeInput`.

**How to reproduce it (as minimally and precisely as possible)?**

The easiest way is to:

1. Run the CSI driver
2. Use the [csc tool](https://github.com/rexray/gocsi/tree/master/csc) to create 2 volumes:

```
$ csc controller new --endpoint tcp://127.0.0.1:10000 (..) && \
  csi controller new --endpoint tcp://127.0.0.1:10000(...)
```

### PR DESCRIPTION
**Pull request by AndyXiangLi**
**Is this a bug fix or adding new feature?**
Fixes #165 

**What is this PR about? / Why do we need it?**
EBS team has updated the createVolume api to accept ClientToken in the createVolume request. doc [here](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.4)
With ClientToken, EBS will be able to ensure the createVolume Idempotency at Api level.
 I think it is ok to keep inflight cache as it is, it ensure the driver level idempotency, and this change is more on the api level.
**What testing is done?** 
unit test
sanity test
Manually tested described in the original re-produce step and observed only one volume is created
```
csc controller create-volume -e <endpoint> --cap 1,1 xiang-test --req-bytes 1024000 & \
> csc controller create-volume -e <endpoint> --cap 1,1 xiang-test --req-bytes 1024000
[1] 2801280
Create volume request for xiang-test is already in progress

Please use -h,--help for more information
"vol-0c8323ca0f9ab1a6d"	1073741824

### CODE REVIEW

File: pkg/driver/controller.go [hunk 1]
```diff
@@ -115,19 +115,6 @@ func (d *controllerService) CreateVolume(ctx context.Context, req *csi.CreateVol
 	}
 	defer d.inFlight.Delete(volName)
 
-	disk, err := d.cloud.GetDiskByName(ctx, volName, volSizeBytes)
```
Comment (AndyXiangLi) [inline pkg/driver/controller.go:118]: With the volumeName in the ClientToken, we no longer need describeVolume to check if the volume has already been created or not. But we will also lose some visibility to customer, if the two createVolume requests have same clientToken(volumeName) but different parameters (size or snapshotId), ebs api will return general idempotency violation exception. (instead of saying diff size or diff snapshotId)

Open to any idea, if you want me to add it back

Comment (vdhanan) [reply pkg/driver/controller.go:118]: i'm good with removing this code

File: pkg/cloud/cloud_test.go [hunk 2]
```diff
@@ -203,6 +203,30 @@ func TestCreateDisk(t *testing.T) {
...
 			expCreateVolumeErr:   fmt.Errorf("CreateVolume generic error"),
 		},
+		{
+			name:       "fail: ec2.CreateVolume returned snapshot not found error",
+			volumeName: "vol-test-name-error",
+			diskOptions: &DiskOptions{
+				CapacityBytes:    util.GiBToBytes(1),
+				Tags:             map[string]string{VolumeNameTagKey: "vol-test", AwsEbsDriverTagKey: "true"},
+				AvailabilityZone: expZone,
+			},
```
Comment (vdhanan) [inline pkg/cloud/cloud_test.go:213]: i'm confused by this test case. don't you need a snapshot ID in the diskOptions to get a Snapshot not found error?

Comment (AndyXiangLi) [reply pkg/cloud/cloud_test.go:213]: It's testing [cloud.go](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L350) so we don't need to actually provide a valid snapshotId, this test case just expect go sdk to return snapshot not found fault code to the client and see if client can handle the error properly.

Comment (vdhanan) [reply pkg/cloud/cloud_test.go:213]: i see. we're just checking that the error gets handled. makes sense.

**Comment by vdhanan** [comment]
let's remove the vendor directory soon haha. these PRs are unnecessarily big

**Comment by AndyXiangLi** [comment]
> let's remove the vendor directory soon haha. these PRs are unnecessarily big

Yeah, agree
