### PR TITLE
instance metadata issue fix

### LINKED ISSUE #474: Cannot Run with IAM Service Account and no metadata service
/kind bug

**What happened?**
The ebs-plugin container on the ebs-csi-controller crashes repeatedly while talking to the metadata service:

```
I0325 19:25:18.560010       1 driver.go:62] Driver: ebs.csi.aws.com Version: v0.6.0-dirty
panic: EC2 instance metadata is not available

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newNodeService(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/node.go:83 +0x196
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0xc00016ff70, 0x3, 0x3, 0xc0000a88a0, 0xdcc3a0, 0xc0001edb00)
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:87 +0x512
main.main()
	/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:31 +0x117
```

**What you expected to happen?**

When specifying the AWS_REGION variable, and an IAM role service account, the ebs-csi-driver should not need to access the metadata service, and run on its own.

**How to reproduce it (as minimally and precisely as possible)?**
1. Create an IAM role with permissions for the aws-ebs-csi-driver
2. Create an EKS cluster with an OIDC connect provider trust relationship with IAM (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), especially following the final step of disabling pods from accessing the metadata service to prevent them from assuming the worker instance profile.
3. Deploy aws-ebs-csi-driver using the alpha kustomize overlays, adding the eks.amazonaws.com/role-arn to the service account
4. The ebs-csi-controller pods will start and crash after about 20s

**Anything else we need to know?**:
As far as we can tell everything is set up correctly with the role + service account, but the code explicitly tries to instantiate the metadata service, which is firewalled off. Can this be made optional if region is set, and credentials are available via the service account?

**Environment**
EKS v1.14
ebs-csi-driver v0.5.0, v0.6.0-dirty

### PR DESCRIPTION
**Pull request by vdhanan**
**Is this a bug fix or adding new feature?**
bug fix (fixes #474)

**What is this PR about? / Why do we need it?**
alternative way to fetch instance metadata

**What testing is done?** 
manual and unit testing

messed up my original PR #846 this is a replacement for that one

### CODE REVIEW

File: pkg/cloud/metadata.go [hunk 1]
```diff
@@ -69,13 +75,69 @@ func (m *Metadata) GetOutpostArn() arn.ARN {
...
+	config, err := rest.InClusterConfig()
+	if err != nil {
+		return nil, err
+	}
+	// creates the clientset
+	clientset, err := kubernetes.NewForConfig(config)
+	if err != nil {
+		return nil, err
+	}
+	return NewMetadataService(svc, clientset)
```
Comment (wongma7) [inline pkg/cloud/metadata.go:88]: IMO we should wrap this error in something helpful. like: error getting information from metadata service or node object : err. Looking back at the issue where people reported that the driver couldnt run because of metadata being unavailable, some context would have helped, because otherwise the driver just crashes with weird error.

File: pkg/cloud/metadata.go [hunk 2]
```diff
@@ -69,13 +75,69 @@ func (m *Metadata) GetOutpostArn() arn.ARN {
 func NewMetadata() (MetadataService, error) {
 	sess := session.Must(session.NewSession(&aws.Config{}))
 	svc := ec2metadata.New(sess)
-	return NewMetadataService(svc)
+	// creates the in-cluster config
+	config, err := rest.InClusterConfig()
+	if err != nil {
+		return nil, err
```
Comment (wongma7) [inline pkg/cloud/metadata.go:81]: I think we shouldonly do this if metadata is unavailable.

File: pkg/cloud/metadata.go [hunk 3]
```diff
@@ -69,13 +75,69 @@ func (m *Metadata) GetOutpostArn() arn.ARN {
...
+			return nil, err
+		}
+
+		providerID := node.Spec.ProviderID
+		if providerID == "" {
+			return nil, fmt.Errorf("node providerID empty, cannot parse")
+		}
+
+		awsRegionRegex := "([a-z]{2}(-gov)?)-(central|(north|south)?(east|west)?)-[0-9]"
+		awsAvailabilityZoneRegex := "([a-z]{2}(-gov)?)-(central|(north|south)?(east|west)?)-[0-9][a-z]"
```
Comment (wongma7) [inline pkg/cloud/metadata.go:112]: @ayberk will this owrk in outpost world?

File: pkg/cloud/metadata_test.go [hunk 4]
```diff
@@ -207,6 +368,31 @@ func TestNewMetadataService(t *testing.T) {
 				if m.GetOutpostArn() != tc.outpostArn {
 					t.Fatalf("GetOutpostArn() failed: expected %v, got %v", tc.outpostArn, m.GetOutpostArn())
 				}
+			} else if !tc.isAvailable {
+				if tc.name == "success: metadata not available, used k8s api" {
+					if err != nil {
+						t.Fatalf("NewMetadataService() failed: expected no error, got %v", err)
+					}
+					if m.GetInstanceID() != "i-abcdefgh123456789" {
```
Comment (wongma7) [inline pkg/cloud/metadata_test.go:376]: these could be consts to facilitate hypothetical future refactoring. doesn't mucvh matter though, just nitpicking.

**Review by wongma7 — APPROVED** [review]

File: pkg/cloud/metadata.go (hunk 2 above)
Comment (vdhanan) [reply pkg/cloud/metadata.go:81]: you're right. i'll change lines 80 and 85 to
`if err != nil && !svc.Available() {`

File: pkg/cloud/metadata.go (hunk 1 above)
Comment (vdhanan) [reply pkg/cloud/metadata.go:88]: can you confirm that this is the idiomatic way to wrap errors?
`func NewMetadata() (MetadataService, error) {
	sess := session.Must(session.NewSession(&aws.Config{}))
	svc := ec2metadata.New(sess)
	// creates the in-cluster config
	config, err := rest.InClusterConfig()
	if err != nil && !svc.Available() {
		return nil, err
	}
	// creates the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil && !svc.Available() {
		return nil, err
	}
	metadataService, err := NewMetadataService(svc, clientset)
	if err != nil {
		err = fmt.Errorf("error getting information from metadata service or node object: %w", err)
	}
	return metadataService, err
}`

File: pkg/cloud/metadata.go (hunk 3 above)
Comment (vdhanan) [reply pkg/cloud/metadata.go:112]: i didn't really consider local zones, wavelength, or outposts when i wrote the regular expression. how much does that matter for GA?

Comment (wongma7) [reply pkg/cloud/metadata.go:112]: of those, i think only outpost matters in the sense that we explicitly said we support it. But, on second thought, even if the regex is edited to be more exhaustive to include the outpost case, it will not help them, because outpost users are still reliant on instance metadata being available to retrieve outpost-id..

Comment (wongma7) [reply pkg/cloud/metadata.go:112]: so for now let's just keep it as is I guess

Comment (vdhanan) [reply pkg/cloud/metadata.go:112]: cool cool

Comment (wongma7) [reply pkg/cloud/metadata.go:112]: to be specific, we have no way to find out if we are on an outpost and to retrieve outpostArn in case metadata is disabled.

**Comment by wongma7** [comment]
/lgtm

feel free to squash, i think im going to have to manually merge anyway if coveralls keeps complaining

File: charts/aws-ebs-csi-driver/Chart.yaml [hunk 5]
```diff
@@ -2,7 +2,7 @@ apiVersion: v1
 appVersion: "0.10.1"
 name: aws-ebs-csi-driver
 description: A Helm chart for AWS EBS CSI Driver
-version: 0.10.3
+version: 0.10.4
```
Comment (wongma7) [inline charts/aws-ebs-csi-driver/Chart.yaml:5]: we can hold off on a helm release. it won't hurt, but it will also be pointless. Because the chart will include the new RBAC objects, but 0.10.1 of the driver doesnt need them yet.

**Comment by wongma7** [comment]
I'm going to merge, because coveralls is still complaining, and the lates tcommit was just changing helm chart and there's no need to retest.

File: pkg/cloud/metadata.go (hunk 3 above)
Comment (ayberk) [reply pkg/cloud/metadata.go:116]: What does the `providerId` look like?

There's a case to be made here to allow customers to set outpost-arn themselves so they can use it without the metadata service. I don't think it's a big deal for now but something to consider.

Comment (vdhanan) [reply pkg/cloud/metadata.go:116]: `providerId` looks like `aws:///us-west-2b/i-abcdefgh123456789`
