### PR TITLE
delete leaked volume if driver don't know the volume status

### LINKED ISSUE #754: Volumes may leak during Create operation: Delete/clean volume if waitForVolume fails during Create operation
/kind bug

If AWS API is unavailable (e.g. due to throttling) then waitForVolume could fail even though the volume eventually becomes available and leaks. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L343

Issue also affects in-tree

### PR DESCRIPTION
**Pull request by AndyXiangLi**
**Is this a bug fix or adding new feature?**
Fixes #754 
**What is this PR about? / Why do we need it?**
Delete volume if the driver don't know about the volume status after creation
**What testing is done?** 
Could see this log after denying DescribeVolume api call manually
```volume is deleted because it is not in desired state within retry limit```
Added unit test

### CODE REVIEW

File: pkg/cloud/cloud_test.go [hunk 1]
```diff
@@ -194,7 +195,8 @@ func TestCreateDisk(t *testing.T) {
 				Tags:             map[string]string{VolumeNameTagKey: "vol-test"},
 				AvailabilityZone: "",
 			},
-			expErr: fmt.Errorf("failed to get an available volume in EC2: timed out waiting for the condition"),
+			cleanUpFailedVolume: true,
+			expErr:              fmt.Errorf("failed to get an available volume in EC2: timed out waiting for the condition"),
```
Comment (wongma7) [inline pkg/cloud/cloud_test.go:199]: I think the test case above (DescribeVolume error ) we should also expect to clean up.

(the test case names are a bit confusing since CreateVolume could mean ec2.createvolume or csi.createvolume. If it helps and you dont mind could you disambiguate them in the test names)

File: pkg/cloud/cloud.go [hunk 2]
```diff
@@ -343,6 +343,13 @@ func (c *cloud) CreateDisk(ctx context.Context, volumeName string, diskOptions *
 	}
 
 	if err := c.waitForVolume(ctx, volumeID); err != nil {
+		// To avoid leaking volume, we should delete the volume just created
+		// TODO: Need to figure out how to handle DeleteDisk failed scenario instead of just log the error
+		if _, error := c.DeleteDisk(ctx, volumeID); error != nil {
```
Comment (ayberk) [inline pkg/cloud/cloud.go:348]: So delete works if the volume is not available when we make the call?

Comment (AndyXiangLi) [reply pkg/cloud/cloud.go:348]: Yeah, I did a test on my account. One concern here is  if the deleteVolume call failed as well then we can not prevent the volume get leaked anyway..

Comment (ayberk) [reply pkg/cloud/cloud.go:348]: Sure, that makes sense.

File: pkg/cloud/cloud_test.go (hunk 1 above)
Comment (ayberk) [reply pkg/cloud/cloud_test.go:199]: +1

Comment (AndyXiangLi) [reply pkg/cloud/cloud_test.go:200]: updated

**Comment by AndyXiangLi** [comment]
Cherry pick upstream fix back to v1.21
https://github.com/kubernetes/kubernetes/pull/100934
