### PR TITLE
Fix CreateVolumeResponse after snapshot restore

### LINKED ISSUE #444: Failed to restore snapshot in 1.17
/kind bug

**What happened?**
I deployed the driver with snapshotter v2.0.0 (i.e. v1beta1 implementation) and took a snapshot of a volume. When I tried to restore it, external-provisioner failed with:

```
failed to provision volume with StorageClass "ebs-sc": volume content source missing
```

From the [provisioner sources](https://github.com/kubernetes-csi/external-provisioner/blob/8444597be20f8739eae1be5a0d9aa5c2eb6cbf91/pkg/controller/controller.go#L617-L628) it's clear that it expects `CreateVolumeResponse.ContentSource` to be set by the CSI driver.

**Environment**
- Kubernetes version (use `kubectl version`): 1.17.0
- Driver version: `amazon/aws-ebs-csi-driver:latest` (as of today)

Full provisioner logs with CreateVolume requests and response:

```
I0129 15:23:02.592199       1 controller.go:853] VolumeContentSource_Snapshot {Snapshot:snapshot_id:"snap-078e5dee44fe28cfa" }
I0129 15:23:02.592228       1 controller.go:861] Requested volume size is 1073741824 and snapshot size is 1073741824 for the source snapshot mysnap
I0129 15:23:02.592294       1 controller.go:523] CreateVolumeRequest {Name:pvc-4ca0d911-20f0-451d-b18a-4ca256521c25 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[] Secrets:map[] VolumeContentSource:snapshot:<snapshot_id:"snap-078e5dee44fe28cfa" >  AccessibilityRequirements:requisite:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2a" > > requisite:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2b" > > requisite:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2c" > > preferred:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2b" > > preferred:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2c" > > preferred:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2a" > >  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0129 15:23:02.592391       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0129 15:23:02.592403       1 connection.go:183] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2b"}},{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2c"}},{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2a"}}],"requisite":[{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2a"}},{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2b"}},{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2c"}}]},"capacity_range":{"required_bytes":1073741824},"name":"pvc-4ca0d911-20f0-451d-b18a-4ca256521c25","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"snap-078e5dee44fe28cfa"}}}}
I0129 15:23:09.111510       1 connection.go:185] GRPC response: {"volume":{"accessible_topology":[{"segments":{"topology.ebs.csi.aws.com/zone":"us-east-2b"}}],"capacity_bytes":1073741824,"volume_id":"vol-0b5fe623befc59833"}}
I0129 15:23:09.112857       1 connection.go:186] GRPC error: <nil>
I0129 15:23:09.112878       1 controller.go:578] create volume rep: {CapacityBytes:1073741824 VolumeId:vol-0b5fe623befc59833 VolumeContext:map[] ContentSource:<nil> AccessibleTopology:[segments:<key:"topology.ebs.csi.aws.com/zone" value:"us-east-2b" > ] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

### PR DESCRIPTION
**Pull request by jsafrane**
CSI wants CreateVolumeResponse.ContentSource to be set to the snapshot that has just been restored.

Fixes #444

### CODE REVIEW

File: pkg/driver/controller.go [hunk 1]
```diff
@@ -154,9 +154,14 @@ func (d *controllerService) CreateVolume(ctx context.Context, req *csi.CreateVol
 		}
 	}
 
+	snapshotID := ""
+	if snapshotSource := req.VolumeContentSource.GetSnapshot(); snapshotSource != nil {
+		snapshotID = snapshotSource.SnapshotId
```
Comment (leakingtapan) [inline pkg/driver/controller.go]: Do we need to set the snapshot ID for an existing volume? Or only at line 188 here 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/446/files#diff-61566437d9b17d18936960aa0bce1ad4R187-R196

for restoring/creating the volume out of snapshot

File: pkg/driver/controller.go [hunk 2]
```diff
@@ -154,9 +154,14 @@ func (d *controllerService) CreateVolume(ctx context.Context, req *csi.CreateVol
...
+	}
+
 	// volume exists already
 	if disk != nil {
-		return newCreateVolumeResponse(disk), nil
+		return newCreateVolumeResponse(disk, snapshotID), nil
```
Comment (leakingtapan) [inline pkg/driver/controller.go]: I would prefer snapshot ID be part of the disk struct

**Comment by leakingtapan** [comment]
Could you add some unit test for it? thx

File: pkg/driver/controller.go (hunk 1 above)
Comment (jsafrane) [reply pkg/driver/controller.go]: Yes, for idempotency. Responses to repeated CreateVolume requests for snapshot restore must have the same fields as the initial response.

File: pkg/driver/controller.go (hunk 2 above)
Comment (jsafrane) [reply pkg/driver/controller.go]: Added. But it moves us further away from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/393

**Comment by jsafrane** [comment]
> Could you add some unit test for it?

There were no snapshot restore tests. I added some.

I added also a check if existing volume was created from expected snapshot, for repeated requests.

**Comment by jsafrane** [comment]
`VpcLimitExceeded: The maximum number of VPCs has been reached.`
/retest
