### PR TITLE
modify error message when request volume is in use with other node

### LINKED ISSUE #515: Wrong Error Returned When Volume is Attached
/kind bug

**What happened?**
When a EBS volume is attached to another EC2 instance the `ALREADY_EXISTS` error is returned when it seems like the `FAILED_PRECONDITION` error should be returned instead because the `node_id` and `volume_id` do not match what the request attachment of `volume_id` and `node_id`. 

CSI Spec: https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerpublishvolume-errors

**What you expected to happen?**
I expected a `FAILED_PRECONDITION` error to be thrown or have this error thrown if the volume was already attached to my node/ec2-instance.

**How to reproduce it (as minimally and precisely as possible)?**
1. Attach a EBS volume to a ec2-instance using any method, easiest would likely be calling 'CreateVolume`, and go through the normal attachment process or by scheduling a job.

2. Call the RPC `ControllerPublishVolume` with the same `volume_id` but different `node_id` than the already attached volume. 

**Anything else we need to know?**:
I've located the line that produces this problem here:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/db95482f8963350d70e9932b0936e6794fe76bf2/pkg/cloud/cloud.go#L358

It would be ideal to have this `ALREADY_EXISTS` still work but just also check for the `node_id` that it is attached to before returning that and otherwise return `FAILED_PRECONDITION`.

**Environment**
- Kubernetes version (use `kubectl version`): N/A (Using Nomad v0.11.2)
- Driver version: v0.6.0-dirty

### PR DESCRIPTION
**Pull request by AndyXiangLi**
**Is this a bug fix or adding new feature?**
Fixes #515 
**What is this PR about? / Why do we need it?**
According to https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerpublishvolume-errors
We are returning wrong error code and error message when volume already assigned to different node
TODO: add logic to handle ALREADY_EXISTS scenario 
**What testing is done?** 
Sanity test passed
Added unit tests

### CODE REVIEW

File: pkg/cloud/cloud.go [hunk 1]
```diff
@@ -115,6 +115,9 @@ var (
 	// ErrAlreadyExists is returned when a resource is already existent.
 	ErrAlreadyExists = errors.New("Resource already exists")
 
+	// ErrAlreadyExists is returned when a resource is already existent.
```
Comment (ayberk) [inline pkg/cloud/cloud.go:118]: Hehe a copy-paste artifact here I see :)

File: pkg/cloud/cloud.go [hunk 2]
```diff
@@ -115,6 +115,9 @@ var (
 	// ErrAlreadyExists is returned when a resource is already existent.
 	ErrAlreadyExists = errors.New("Resource already exists")
```
Comment (ayberk) [inline pkg/cloud/cloud.go:116]: Do we not use this anymore?

Comment (ayberk) [reply pkg/cloud/cloud.go:116]: Ok I see the TODO below.

File: pkg/cloud/cloud.go [hunk 3]
```diff
@@ -1044,3 +1052,14 @@ func volumeModificationDone(state string) bool {
 	}
 	return false
 }
+
+func getVolumeAttachmentsList(volume *ec2.Volume) []string {
+	var volumeAttachmentList []string
+	if len(volume.Attachments) > 0 {
```
Comment (ayberk) [inline pkg/cloud/cloud.go:1058]: Do you need this check?

File: pkg/driver/controller.go [hunk 4]
```diff
@@ -286,19 +286,21 @@ func (d *controllerService) ControllerPublishVolume(ctx context.Context, req *cs
...
 		return nil, status.Errorf(codes.Internal, "Could not get volume with ID %q: %v", volumeID, err)
 	}
 
+	// If given volumeId already assigned to given node, will directly return current device path
 	devicePath, err := d.cloud.AttachDisk(ctx, volumeID, nodeID)
 	if err != nil {
-		if err == cloud.ErrAlreadyExists {
-			return nil, status.Error(codes.AlreadyExists, err.Error())
+		if err == cloud.ErrVolumeInUse {
+			return nil, status.Error(codes.FailedPrecondition, strings.Join(disk.Attachments, ","))
```
Comment (ayberk) [inline pkg/driver/controller.go:301]: I don't think this is what we want. Looking at the API documentation[[1]][[2]], this list will have information about previous attachments as well, but the status will be "detached". So I think what we want to do is filter for "attached". 

[1]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Volume.html
[2]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VolumeAttachment.html

File: pkg/driver/controller_test.go [hunk 5]
```diff
@@ -2697,7 +2697,7 @@ func TestControllerPublishVolume(t *testing.T) {
 					if !ok {
 						t.Fatalf("Could not get error status code from error: %v", srvErr)
 					}
-					if srvErr.Code() != codes.AlreadyExists {
+					if srvErr.Code() != codes.FailedPrecondition {
```
Comment (ayberk) [inline pkg/driver/controller_test.go:2700]: Can we also check if we're returning the correct instance id in the error message? It's a requirement from the spec.

File: pkg/cloud/cloud.go (hunk 3 above)
Comment (AndyXiangLi) [reply pkg/cloud/cloud.go:1058]: You are right, we actually not need this.

File: pkg/driver/controller.go (hunk 4 above)
Comment (AndyXiangLi) [reply pkg/driver/controller.go:301]: Yeah, this is a good point, will update

File: pkg/cloud/cloud.go [hunk 6]
```diff
@@ -1044,3 +1052,14 @@ func volumeModificationDone(state string) bool {
 	}
 	return false
 }
+
+func getVolumeAttachmentsList(volume *ec2.Volume) []string {
+	var volumeAttachmentList []string
+	for _, attachment := range volume.Attachments {
+		if attachment.State != nil && aws.StringValue(attachment.State) == "attached" {
```
Comment (ayberk) [inline pkg/cloud/cloud.go:1059]: Can we lowercase `aws.StringValue(attachment.State)` just to be safe?
